sudo: false

os:
  - linux

language: node_js

node_js:
  - 8

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

# install:
#   - npm install
#   - npm run vscode:prepublish

# script:
#   - npm test --silent

env:
  global:
    secure: gHlfBzgg2aA3sjRUTouFzOrVp7hjZhrynX1yo3QRE+G1j8qFWoxx1Z5YSq/cLBDCCHoVmulOSoVB8SzhcCfhADl/znIc3DZl/zAhDlNQUAU+ILonVk/DTLO8gkv9IbXXNZ8JUpMwwKzrPeC2w216fPPNSowFVwiPbekWqmVHkjf0mGlSzDK2IEeFdu+8NpZGi0o6v2f29Ho9JMoXnP9H2pmGJHsZYOu3fXEq2/P6bj91xmjQ9uTDPj+evcnzZlbKJLOFr5Jax8qi1otyP1bdbwiOJ76KzGu89ek5ir9ZKTt3zum8KjWyKzqXmCap6/ctt7+MM15b5xrAiKBVHH95YdQnmBrtr82YEG/pCRqLoa+vzdQvEB1zRBmxpAQUtF1bb9+oJP6HQgP3c4TZoB0u3fxOJfr+FGywFqmDWNvsmI2IaxOgUyeMmHc6hD3U4pjverPp5ODZx1limpxu3+NQMubWP5BSRJhMUPFqj4DcjzSJ8+8jGxM7nYSmQjJy7kC61hwmd/5GgnX+ClB5p9jVjlrTEga8cKw4cxjjkIl3h05zVVt/a8itRcgrXggwKSbHTtYiPcpP3no2fH2k5jFg812u6hzKIvrVvPla7BzlZxYFbGH7FTklOcO3Dp4ElWedK+uQA9d9b+ztFOfbKZfVgCNmyCcXImdS9ZLRJ8VyvOc=

after_success:
- npm install -g vsce;
- vsce package;

deploy:
- provider: releases
  api_key:
    secure: jgk0CbFQVlMonCXzy9GwpKVxWHR3e8lz/wfYKP7BiKOH5w6BOvfX1SY92oFYx/+esYZXtx3Am9SFXju0aDcE5lvZMpQfana20qZJW2a4x1M0Pgex2zU1Qho4ebcyIamJUycgVYDo0U9+X1rTjGS4KlmYBF5n9J17bo+m6SJmqP9+aNQ+1N8lCzWYIdaUKzyUOn6UyDf47/SGlro9QCUEfLCWO+kIiEn9zJE+Yp+GOvv2whAzfTBXgUZFtzXu7jU268xdyiiYy2VdrX2LmlzcCsxiryFBpYHZAdH1ye6+XQsGLxp/fLiPVWX63x+LIIIPmAVYEJkJBpvMtVkaeTW3YyX9RMMXUljWK+uBvbpoLC/2a1jCKS4+G8u0o/YjPmwjdejWBwCs8H0YzaEwkASjme9Xn91HBSzaOACsVzjO5pJqpl/ij43u/uVIZPlUceWRC1xitqGbu8A1JizfYIQ+gvQirfuR93v/F1/VrWIeuj3WcCSWzBywVku7S3IAY6fXd8C2XY9cyAjeFzeLU6X/ld/BIFnCF+kUuyuqn0IH6A/QlKBaFsjGJESTeDKIXIRYXAF3Rj+7QQzulyPow5i6q4VQrzkcevEGW1kftFrPFu9NZ9YImms60x3BMD56IQLHQRHn+0pqHyfNmM1qVE+7GuW+TJs4rA1AJHRSvcL/Po4=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: DavidBabel/vscode-simpler-icons
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: DavidBabel/vscode-simpler-icons
    tags: true
    condition: $TRAVIS_OS_NAME = linux
